import ExtensionAPI from 'sap/fe/core/ExtensionAPI';                                                                                                                                                                                                           
import Context from 'sap/ui/model/odata/v4/Context';                                                                                                                                                                                                           
import MessageToast from 'sap/m/MessageToast';                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                               
export default {                                                                                                                                                                                                                                               
&nbsp;&nbsp;&nbsp;                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                               
    /**                                                                                                                                                                                                                                                        
     * Generated event handler for Back button.                                                                                                                                                                                                                
     *                                                                                                                                                                                                                                                         
     * @param this reference to the 'this' that the event handler is bound to.                                                                                                                                                                                 
     * @param pageContext the context of the page on which the event was fired                                                                                                                                                                                 
     */                                                                                                                                                                                                                                                        
    onBack: function(this: ExtensionAPI, pageContext: Context) {&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                                                                                                                                               
        window.history.back();                                                                                                                                                                                                                                 
    },                                                                                                                                                                                                                                                         
&nbsp;&nbsp;&nbsp;                                                                                                                                                                                                                                             
};                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                               