import ControllerExtension from 'sap/ui/core/mvc/ControllerExtension';                                                                                                                                                                                         
import ExtensionAPI from 'sap/fe/templates/ObjectPage/ExtensionAPI';                                                                                                                                                                                           
import Button from 'sap/m/Button';                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                               
/**                                                                                                                                                                                                                                                            
 * @namespace factorycalendarexception.ext.controller                                                                                                                                                                                                          
 * @controller                                                                                                                                                                                                                                                 
 */                                                                                                                                                                                                                                                            
// Add a declaration for sap.ushell.Container to satisfy TypeScript                                                                                                                                                                                            
declare global {                                                                                                                                                                                                                                               
	namespace sap {                                                                                                                                                                                                                                               
		namespace ushell {                                                                                                                                                                                                                                           
			const Container: any;                                                                                                                                                                                                                                       
		}                                                                                                                                                                                                                                                            
	}                                                                                                                                                                                                                                                             
}                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                               
export default class ObjectPageExt extends ControllerExtension<ExtensionAPI> {                                                                                                                                                                                 
	static overrides = {                                                                                                                                                                                                                                          
		/**                                                                                                                                                                                                                                                          
		 * Called when a controller is instantiated and its View controls (if available) are already created.                                                                                                                                                        
		 * Can be used to modify the View before it is displayed, to bind event handlers and do other one-time initialization.                                                                                                                                       
		 * @memberOf factorycalendarexception.ext.controller.ObjectPageExt                                                                                                                                                                                           
		 */                                                                                                                                                                                                                                                          
		onInit(this: ObjectPageExt) {                                                                                                                                                                                                                                
			// you can access the Fiori elements extensionAPI via this.base.getExtensionAPI                                                                                                                                                                             
			const model = this.base.getExtensionAPI().getModel();                                                                                                                                                                                                       
			console.log("Test");                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                               
		},                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                               
		onAfterRendering(this: ObjectPageExt){                                                                                                                                                                                                                       
			                                                                                                                                                                                                                                                            
			// This method is called after the view has been rendered.                                                                                                                                                                                                  
			const backBtn = this.base.getExtensionAPI().byId("factorycalendarexception::ZC_FC_EXCEPTIONSObjectPage--fe::CustomAction::BACK") as Button;                                                                                                                 
                                                                                                                                                                                                                                                               
			if (backBtn && sap.ushell.Container){		                                                                                                                                                                                                                     
				backBtn.setVisible(false)                                                                                                                                                                                                                                  
			}                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                               
		}                                                                                                                                                                                                                                                            
	                                                                                                                                                                                                                                                              
	}                                                                                                                                                                                                                                                             
}                                                                                                                                                                                                                                                              