CLASS zcx_fc_error DEFINITION
  PUBLIC
  INHERITING FROM cx_static_check
  CREATE PUBLIC .

  PUBLIC SECTION.
    INTERFACES: if_t100_dyn_msg.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcx_fc_error IMPLEMENTATION.
ENDCLASS.
